version: 2.1

########################## Setup References ##########################
references:

working_directory: &working_directory
  ~/project

default_config: &default_config
  docker:
    - image: hashicorp/terraform:light
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc
    TERRAFORM_ENV: ~/project/

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

########################## Pre-configure steps ##########################

restore_repo: &restore_repo
  restore_cache:
    name: Restore Cache
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    name: Save Cache
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      cd && touch $BASH_ENV
      cd ~/project/

# terraform init step
terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      cd ~/project/
      terraform init -backend-config="token=${TF_API_TOKEN}"
      ls -lahrt


########################## Job Definitions ##########################

jobs:

  build:
    <<: *default_config
    steps:
      - checkout
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform fmt
          command: |
            source $BASH_ENV
            cd ~/project/
            terraform fmt
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      #- *terraform_init
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            cd ~/project/
            terraform plan

  apply:
    apply_job:
      <<: *default_config
      steps:
        - *restore_repo
        - *set_terraform_environment
      #  - *terraform_init
        - attach_workspace:
            at: *working_directory
        - run:
            name: terraform apply
            command: |
              source $BASH_ENV
              cd ~/project/
              terraform init -backend-config="token=${TF_API_TOKEN}"
              terraform apply --auto-approve

  destroy:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
     # - *terraform_init
      - run:
          name: "Destruction of env"
          command: |
            source $BASH_ENV
            cd ~/project/
            terraform destroy --auto-approve

########################## Workflow ##########################
workflows:
  version: 2.0
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build

      - apply:
          requires:
            - plan
          filters:
            branches:
              only:
                - master

#      - hold:
#          type: approval
#      - destroy:
#          requires:
#            - hold